
//----------------------------------------------------
// The following code was generated by CUP v0.10k TUM Edition 20050516
// Fri Oct 07 17:07:06 CEST 2016
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PARD = 3;
  public static final int STRING = 2;
  public static final int error = 1;
  public static final int EOF = 0;
  public static final int PARG = 4;
}

