
//----------------------------------------------------
// The following code was generated by CUP v0.10k TUM Edition 20050516
// Fri Oct 21 16:28:49 CEST 2016
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LP = 6;
  public static final int MULT = 5;
  public static final int EOF = 0;
  public static final int PLUS = 2;
  public static final int NL = 8;
  public static final int DIV = 4;
  public static final int error = 1;
  public static final int MOINS = 3;
  public static final int NB = 9;
  public static final int RP = 7;
}

