
//----------------------------------------------------
// The following code was generated by CUP v0.10k TUM Edition 20050516
// Thu Dec 08 12:02:01 CET 2016
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PAR_GAUCHE = 56;
  public static final int EXECUTER_SCENARIO = 46;
  public static final int PAR_DROITE = 57;
  public static final int CHEVRON_GAUCHE = 63;
  public static final int FERMER = 29;
  public static final int VIRGULE = 68;
  public static final int TELEPHONE = 10;
  public static final int AUTRE_APPAREIL = 7;
  public static final int FENETRE = 6;
  public static final int FERMER_PARTIEL = 37;
  public static final int SI = 41;
  public static final int LAVE_VAISSELLE = 17;
  public static final int ALARME = 5;
  public static final int ALLUMER = 31;
  public static final int FERME = 27;
  public static final int ETAT = 33;
  public static final int EGALITE = 61;
  public static final int AFFECTATION = 60;
  public static final int CAFETIERE = 15;
  public static final int OUVRIR_PARTIEL = 36;
  public static final int DECLARATION_APPAREILS = 51;
  public static final int DECLARATION_INTERFACES = 52;
  public static final int CHAINE = 72;
  public static final int CHAUFFAGE = 4;
  public static final int TAMISER = 32;
  public static final int ALLUME = 22;
  public static final int DECLARATION_SCENARII = 53;
  public static final int TELECOMMANDE = 11;
  public static final int CHEVRON_DROIT = 64;
  public static final int ASSOCIER = 47;
  public static final int ENTIER = 70;
  public static final int ETEINT = 23;
  public static final int PROGRAMMER = 48;
  public static final int SLASH = 65;
  public static final int PORTAIL = 21;
  public static final int ETEINDRE = 30;
  public static final int FAIT = 40;
  public static final int ALORS = 42;
  public static final int IDENTIFIANT = 71;
  public static final int FAIRE = 39;
  public static final int ECO = 25;
  public static final int ACO_GAUCHE = 58;
  public static final int POURTOUT = 38;
  public static final int DEFINIR = 45;
  public static final int SINON = 43;
  public static final int POINT = 67;
  public static final int OUVERT = 26;
  public static final int LAVE_LINGE = 18;
  public static final int ORDINATEUR = 20;
  public static final int EOF = 0;
  public static final int OUVRIR = 28;
  public static final int SCENARIO = 55;
  public static final int MESSAGE = 49;
  public static final int DEUX_POINT = 69;
  public static final int ECLAIRAGE = 2;
  public static final int UNDERSCORE = 66;
  public static final int ACO_DROITE = 59;
  public static final int INTERRUPTEUR = 8;
  public static final int DEMI = 24;
  public static final int error = 1;
  public static final int ALLUMER_ECO = 35;
  public static final int TABLETTE = 12;
  public static final int MOBILE = 9;
  public static final int VOLET = 3;
  public static final int HIFI = 14;
  public static final int VIDEO_PROJ = 16;
  public static final int POINT_VIRGULE = 62;
  public static final int PROGRAMME_DOMUS = 50;
  public static final int DECLARATION_COMMANDES = 54;
  public static final int TV = 13;
  public static final int ALLUMER_PARTIEL = 34;
  public static final int FSI = 44;
  public static final int SECHE_LINGE = 19;
}

