
//----------------------------------------------------
// The following code was generated by CUP v0.10k TUM Edition 20050516
// Fri Oct 07 15:49:47 CEST 2016
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int STRING = 2;
  public static final int error = 1;
  public static final int EOF = 0;
}

